# Generated by Django 5.2.5 on 2025-08-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_description_alter_mymodel_name_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('ceo', 'CEO'), ('manager', 'Manager'), ('cashier', 'Cashier'), ('chairman', 'Chairman'), ('dispatch', 'Dispatch')], default='cashier', max_length=10),
        ),
    ]
